### ISSUE TITLE
Error: no OccuType field in file

### ISSUE THREAD

**Issue by dacermi** [FloodRiskGroup/floodrisk#5]
There is a problem with the OccuType field. It does not read it correctly, neither with the data of the example provided nor with its own data.
![captura](https://user-images.githubusercontent.com/45595865/49442102-bbbc4d80-f7c8-11e8-87af-c8d200f458df.JPG)

**Comment by FloodRiskGroup** [comment]
The floodrisk script for uploading data adopts a spatialite geodatabase created from an included template (Template.sqlite). To load a shapefile, it must have the "OccuType" field, as written in the manual, and the file of the examble has it. At the same time the geodatabase must have a table called "StructurePoly" having the "OccuType" field as the template geodatabase.
The problem reported could be due to a mismatch of the geodatabase adopted with respect to the template.

**Comment by FPerosa** [comment]
I am having the same problem as dacermi. Even thoug my Property and Infrastructure shapefiles do have a  "OccuType" field (also in text format with 5 characters), they don't seem to be recognized by the program when I upload the shapefiles to the geodatabase. Should the table called "StructurePoly" be automatically created or should I provide it as input? Thank you.

**Comment by FloodRiskGroup** [comment]
The StructurePoly table must exist in the geodatabase when a shapefile is uploaded.
This and all other tables are automatically created when a new geodatabase is created based on the Template.sqlite that is included in the plugin installation.
It may happen that the data structure is corrupt and in this case it is necessary to re-create a new geodatabase from scratch: 
to facilitate this operation I have updated the plugin so that now it is possible to overwrite a corrupted geodatabase with a new one as shown in the figure.

![Open_new](https://user-images.githubusercontent.com/16383004/59412494-d990ed80-8dbd-11e9-862d-2626bacb835f.png)

The update files are on github, while at the same time I requested the QGIS repository update and I am waiting for it to be executed.

**Comment by cefect** [comment]
Having the same problem when using any 'Economic Tangible' 'Exposure' layers from the example 'FloodRiskData_2'. I tried loading the 'GeoDB_Floodrisk_2_template.sqlite', the 'Geodatabase.Sqlite' from the example files, and creating a new one.  All seemed to have a layer 'StructurePoly' with these fields:


OBJECTID | instance | OccuType | Valstr | Valcon | Shape_Length | Shape_Area

while the sample 'PropertyPoly.shp' has these fields:







Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2

**Comment by cefect** [comment]
Having the same problem when using any 'Economic Tangible' 'Exposure' layers from the example 'FloodRiskData_2'. I tried loading the 'GeoDB_Floodrisk_2_template.sqlite', the 'Geodatabase.Sqlite' from the example files, and creating a new one. All seemed to have a layer 'StructurePoly' with these fields:

OBJECTID | instance | OccuType | Valstr | Valcon | Shape_Length | Shape_Area

while the sample 'PropertyPoly.shp' has these fields:

OccuType	Valstr	Valcon	Descr	Shape_Area

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2
